on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
  
    timeout-minutes: 15

    env:
      working-directory: ./src/Segadora.Secvest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/segadora/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
        working-directory: ${{env.working-directory}}
      - name: Push
        run: dotnet nuget push Segadora.Secvest.${VERSION}.nupkg --source https://nuget.pkg.github.com/segadora/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.working-directory}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
